spring:
  data:
    redis:
      port: 26380
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MySQL # 메모리 DB
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false